### ISSUE TITLE
Latest SuperRare Contract Compatibility

### ISSUE THREAD

**Issue by tommymsz006** [protofire/superrare-subgraph#2]
Is the subgraph compatible for SuperRare token contract at [0xb932a70a57673d89f4acffbe830e8ed7f75fb9e0](https://etherscan.io/token/0xb932a70a57673d89f4acffbe830e8ed7f75fb9e0).

I tried to find the latest token IDs (e.g. 8494) but I couldn't get the relevant information.

**Comment by sistemico** [comment]
Just added support for SuperRare V2 recently.

You can get the desired data with the following query:

```graphql
{
  artwork(id: "V2-8494") {
    tokenId
    name
    description
    yearCreated
    imageUri
    tags
    created
    creator {
      id
    }
    owner {
      id
    }
  }
}
```
